const TEST_TYPES = {
    ABSOLUTE_URLS: 'ABSOLUTE_URLS',
    NO_PROTOCOL: 'NO_PROTOCOL',
    NO_WWW: 'NO_WWW',
    NAKED_DOMAIN: 'NAKED_DOMAIN',
    NO_INPUT: 'NO_INPUT',
    SPECIAL_CHARS: 'SPECIAL_CHARS',
    WRONG_DOMAIN: 'WRONG_DOMAIN',
    USERNAME_ONLY: 'USERNAME_ONLY',
    SPACES: 'SPACES',
};

Object.freeze(TEST_TYPES);
module.exports.TEST_TYPES = TEST_TYPES;
