# Workflow for updating release when changes are pushed to master
name: Update Release CI

# Controls when the action will run.
on:
    push
    # Triggers the workflow on push but only for the master branch

jobs:
    publish:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps:
        # 0. Checkout Source Code
        # 1. Check node_modules cache; Install dependencies
        # 2. Test files
        # 3. Check src cache; Skip Remaining if no changes
        # 4. Bump version
        # 5. Build Code
        # 6. Publish to NPM
        # 7. Publish to GitHub
        steps:
            - name: Checkout Source Code
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.ref }}

            - name: Cache node_modules
              id: cache-modules
              uses: actions/cache@v2
              with:
                  path: node_modules
                  key: 14.6.x-${{ runner.OS }}-build-${{ hashFiles('package.json') }}

            - name: Install
              if: steps.cache-modules.outputs.cache-hit != 'true'
              run: yarn install

            - name: Test
              run: yarn test

            - name: Cache src
              id: cache-src
              uses: actions/cache@v2
              with:
                  path: src
                  key: 14.6.x-${{ runner.OS }}-build-${{ hashFiles('src/*') }}

            - name: Build
              if: steps.cache-src.outputs.cache-hit != 'true'
              run: yarn tsc

            - name: Automated Version Bump
              id: version-bump
              if: steps.cache-src.outputs.cache-hit != 'true'
              uses: 'phips28/gh-action-bump-version@master'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Set Up for NPM Publish
              uses: actions/setup-node@v2
              with:
                  node-version: '14.x'
                  registry-url: 'https://registry.npmjs.org'

            - name: Publish to NPM
              # if: steps.cache-src.outputs.cache-hit != 'true'
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

            - name: Set Up for GitHub Publish
              uses: actions/setup-node@v2
              with:
                  node-version: '14.x'
                  registry-url: 'https://npm.pkg.github.com'
                  scope: '@elevatormedia'

            - name: Publish to GitHub
              if: steps.cache-src.outputs.cache-hit != 'true'
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
