name: Test & Build

on: pull_request

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.ref }}

            - name: Use Node.js 14.16.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.16.x

            - name: Cache node_modules
              id: cache-modules
              uses: actions/cache@v1
              with:
                  path: node_modules
                  key: 14.6.x-${{ runner.OS }}-build-${{ hashFiles('yarn.lock') }}

            - name: Install
              if: steps.cache-modules.outputs.cache-hit != 'true'
              run: yarn install

            - name: Test
              run: yarn test

            - name: Build
              run: yarn tsc
